name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Cek apakah branch kamu 'main' atau 'master'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject API Key
        run: |
          # Perintah ini mengganti placeholder di ai.js dengan Secret asli
          sed -i "s/SECRET_GEMINI_KEY_PLACEHOLDER/${{ secrets.GEMINI_API_KEY }}/g" js/ai.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4